# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is autogenerated by the dependency update service and should not be modified directly.
# For more details, check the deps_spec.yaml file in the current folder.

RULES_DOCKER = struct(
    commit = "3772262910d1ac63563e5f1758f07df1f7857442",
    sha256 = "53adff9ab61c7722a8ab8695437493b7bb85bc8ea89bb164b67d965864fadc13",
)

LAYER_DEFINITIONS = struct(
    commit = "4d8b09b741f8709bc536a423e2bda6c4b1c95c3d",
    sha256 = "ae20ef179b5bced88bd10b8a32b084a887e39eb575a8c624036c0220ef682ae6",
)
